jobs:
    build:
        steps:
            - name: run 
            env:
                CLIENT_CERT: ${{ secrets.CLIENT_CERT }}
                CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
                SERVER_CA: ${{ secrets.SERVER_CA }}
            run: gym_lifts_SQL_DB_streamlit_version
